### PR TITLE
footer update

### PR DESCRIPTION
**Pull request by garvitchittora**

### CODE REVIEW

**Comment by thesmallstar** [comment]
great, thanks. 
Can you give a live link?

**Comment by garvitchittora** [comment]
https://garvitchittora.github.io/effe-email/index.html

**Comment by thesmallstar** [comment]
image

I guess the icons would be enough? We don't need to write the names along with it?
What do you think @garvitchittora  @sggts04  @sarthakm21

**Comment by sggts04** [comment]
yea, only the icons in center would be better I think

**Comment by sggts04** [comment]
image
this seems good I think.. @thesmallstar @garvitchittora

**Comment by thesmallstar** [comment]
> this seems good I think.. @thesmallstar @garvitchittora

Let's go with this :)

**Comment by garvitchittora** [comment]
yes sir

**Comment by garvitchittora** [comment]
https://garvitchittora.github.io/effe-email/

**Comment by thesmallstar** [comment]
Great thanks, bringing into the codebase.

**Pull request merged**
